# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty



# Setup
title:            Margot DÃ©age
description:      'Docteure en sociologie'


author:
  name:           'margotdeage'
  url:            https://twitter.com/stalkologist

paginate:         5


theme: jekyll-theme-slate
